apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ms-auth
  namespace: battleships
  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app: ms-auth

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s