apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ms-game
  namespace: battleships
  labels:
    release: kube-prometheus-stack

spec:
  selector:
    matchLabels:
      app: ms-game
      
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s